### ISSUE TITLE
Implementation Guide

### ISSUE THREAD

**Issue by 0ddjob** [mattcallow/CPC_PICOROM#1]
Hey Matt,

Finally got some 50-way edge connectors so I can finally build that board you gave me at the ACMS Amstrad day.  But I'm a bit hazy on the bare-minimum parts needed for the ROM management - I remember you said not everything was needed.

Could you provide more details on the basics needed, and also the process to load the Pico, etc.?  I'd like to make a video about it.

Thanks!
Brett.

**Comment by mattcallow** [comment]
Hi Brett. You can omit the LS688 and the USB module. I'll try to write some better documentation.
Matt

**Comment by 0ddjob** [comment]
Thanks Matt.  I'll start building the board.  I've never used a Pico before - I can kind-of figure out ... maybe ... what needs to be done.  I'm guessing the Python script is used to compile all the separate ROM files into a single file, but not sure what do with the other stuff and how to get it onto the Pico (well, I could probably Google that).

But some clarification on what needs to be done with all the other stuff would be great!

**Comment by mattcallow** [comment]
I've updated the readme to include a section on software installation. Let me know how you go with that.

**Comment by 0ddjob** [comment]
Looks good, I should be able to follow that, thanks!  
I'll give it a try (eventually) on the Plus range as well.  I'm planning to make a simple/universal 50-way Centronics to edge connector PCB first, and if it works, modify your board slightly so the Centronics connector can be soldered directly to it (ordering a few straight-through and right-angle connectors).
Brett.

**Comment by 0ddjob** [comment]
Got it built, going to look for some ROMs now and try to build the firmware.

I don't have a two-way switch handy for the PicoROM enable/disable - I assume I can just hardwire it as enabled?

Brett.

**Comment by mattcallow** [comment]
yes, you can. The switch is just to save removing the board.
